apiVersion: v1 #Kubernetes API version
kind: Pod #Type of Kubernetes resource
metadata:
  name: my-nginx #Some metadata about the Pod
  labels:
    app: nginx
    rel: stable
spec: #The spec/blueprint for the pod
  containers: #Information about the containers that will run in the Pod
  - name: my-nginx
    image: nginx:alpine
    ports:
    - containerPort: 80